language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "stable"

services:
 - mysql

sudo: false

notifications:
  email:
    - dcoates@mozilla.com
    - jrgm@mozilla.com
    - rfkelly@mozilla.com
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm install -g npm@2
  - npm config set spin false

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS fxa'
  - npm i grunt-cli -g

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "stable"
  fast_finish: true
