language: node_js

node_js:
 - "0.10"
 - "0.12"
 - "iojs-v1"
 - "iojs-v2"

services:
 - mysql

notifications:
  irc:
    channels:
      - "irc.mozilla.org#fxa-bots"
    use_notice: false
    skip_join: false

before_install:
  - npm install -g npm@2
  - npm config set spin false

before_script:
  - mysql -e 'DROP DATABASE IF EXISTS fxa'
  - npm i grunt-cli -g
  - npm run outdated
  - grunt validate-shrinkwrap --force

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "iojs-v1"
    - node_js: "iojs-v2"
  fast_finish: true
